# Use tall, wide, and fullscreen layouts
layouts:
    - tall
    - fullscreen
    - wide

# Enable focus-follows-mouse
mouse-follows-focus: false
focus-follows-mouse: false
mouse-resizes-windows: true
mouse-swaps-windows: true

# Add 10px margin between windows
window-margins: true
window-margin-size: 3

# Define which windows should be tiled
floating-is-blacklist: false
floating: ["com.hnc.Discord", "org.mozilla.firefox", "com.google.Chrome", "com.jetbrains.intellij", "com.googlecode.iterm2", "com.apple.mail", "com.apple.MobileSMS", "com.microsoft.Excel", "com.microsoft.Powerpoint", "com.microsoft.Word", "com.jetbrains.pycharm", "com.apple.Safari", "com.tinyspeck.slackmacgap", "com.sublimetext.4", "com.microsoft.VSCode", "com.jetbrains.WebStorm"]
